name: Pull Request Checks
on:
  pull_request: {}

permissions:
  actions: write
  contents: read

jobs:
  codequality:
    name: Check
    uses: ./.github/workflows/codequality.yml
  unit:
    name: Check
    uses: ./.github/workflows/unit.yml
  docker:
    name: Check / Build Docker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build .
